import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "雪山之间",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	const layoutCSS = {
		width: "98vw",
		height: "98vh",
	};

	return (
		<html lang="en">
			<body style={layoutCSS}>{children}</body>
		</html>
	);
}
